services:
  - type: web
    name: codesandbox
    runtime: docker
    dockerfilePath: ./Dockerfile.app
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: GOOGLE_ID
        sync: false
      - key: GOOGLE_SECRET
        sync: false
      - key: GITHUB_ID
        sync: false
      - key: GITHUB_SECRET
        sync: false
